version: '3'
services:
  teleport:
    build: .
    image: docker-teleport
    container_name: teleport_test
    cap_add:
      - SYS_PTRACE
    volumes:
      - "./:/tmp/teleport"
    env_file:
        - teleport.env
    networks:
      default:
        ipv4_address: 172.22.0.2


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/16
